language: c

compiler:
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential pkg-config automake autoconf libtool
  - sudo apt-get install -y libsndfile1-dev

script:
  - ./autogen.sh
  - make
  - make distcheck
