language: c
sudo: false

compiler:
  - gcc

addons:
  apt:
    packages:
    - build-essential
    - pkg-config
    - automake
    - autoconf
    - libtool
    - check
    - libsndfile1-dev

script:
  - ./autogen.sh
  - make
  - make distcheck
